### ISSUE TITLE
Discontinued support for Raycast

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#84]
I just went to https://github.com/pomdtr/sunbeam-raycast to see if there were recent changes (the sunbeam extensions that used to work in Raycast don't anymore) and saw that Raycast support has been dropped.

I am a bit bummed as this was the primary way I accessed my extensions and thought that it would be a great way to share those to users not heavily using the terminal in their day to day.

I understand that you don't want to be tied to Raycast's UI/API, but would it be possible to have a subset of Sunbeam's API compatible with Raycast? e.g. `list` is OK, but not another future UI type

If you don't have time to support Raycast I might fork your existing work and try to get it working again after 1.0 is out but I just wanted to share my use case.

**Comment by pomdtr** [comment]
I have a setup that mirror the raycast experience using the hyper terminal (it supports a global shortcut, and automatically hide when it looses focus). You can find my config it in the extension docs (the main benefit is thatit should also work in linux/windows!)

I'll may try to update the raycast extension after v1, but I want to focus on the TUI experience right now, since it's the highlight of sunbeam compared to raycast right now (ex: watching system resources using htop, running vim from sunbeam to edit a gist...).
